:zap: Add option to use mamba solver, and use it by default (#4)
Enable the `--mamba` option of conda-lock for faster solves.

* :alembic: Check if mamba is installed

See if `pip install conda-lock` actually installs mamba too.

* :heavy_plus_sign: Install conda-lock using micromamba

Use Micromamba to get conda-lock from conda-forge instead of PyPI.

* :zap: Use mamba solver by default

Set the `--mamba` flag to use the faster solver by default. Also need to install `mamba` into the environment.

* [condalock-command] autogenerated conda-lock files

* :wrench: Make usage of mamba solver configurable with boolean flag

Allow the mamba solver to be set via a true/false boolean flag, in case someone wants to not enable it by default. Default is true (use mamba). Documented this setting in the main README.md too.

* :ambulance: Try surrounding conditional statement in quotes

Another try to see if it's possible to get around `Error: /home/runner/work/conda-lock-refresh/conda-lock-refresh/./action.yml: (Line: 55, Col: 38, Idx: 1521) - (Line: 55, Col: 38, Idx: 1521): Mapping values are not allowed in this context.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected`

* :necktie: Use ternary expression instead of json mapping hack

Use ternary expression syntax from https://docs.github.com/en/actions/learn-github-actions/expressions#example. Harder to understand, but should work.

* :memo: Put quotes around strings but not booleans in Action inputs table

Try to make clear that booleans (true/false) shouldn't have quotes around them, but strings should.

---------

Co-authored-by: actions-bot <58130806+actions-bot@users.noreply.github.com>